apiVersion: apps/v1
kind: Deployment
metadata:
  name: Spring-cloud-Kubernetes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Spring-cloud-Kubernetes
  template:
    metadata:
      labels:
        app: Spring-cloud-Kubernetes
    spec:
      containers:
        - name: Spring-cloud-Kubernetes
          image: karthikpilla/Spring-cloud-Kubernetes:latest
