kind: Service
apiVersion: v1
metadata:
  name: kubernetes-configmap.yml
spec:
  type: LoadBalancer
  selector:
    app: kubernetes-configmap.yml
  ports:
    - name: http
      protocol: TCP
      # ELB's port
      port: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-configmap.yml
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-configmap.yml
  template:
    metadata:
      labels:
        app: kubernetes-configmap.yml
    spec:
      containers:
        - name: kubernetes-configmap.yml
          image: karthikpilla/kubernetes-configmap.yml:latest
