kind: Service
apiVersion: v1
metadata:
  name: Spring-cloud-Kubernetes
spec:
  type: LoadBalancer
  selector:
    app: Spring-cloud-Kubernetes
  ports:
    - name: http
      protocol: TCP
      # ELB's port
      port: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Spring-cloud-Kubernetes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Spring-cloud-Kubernetes
  template:
    metadata:
      labels:
        app: Spring-cloud-Kubernetes
    spec:
      containers:
        - name: kubernetes-configmap.yml
          image: karthikpilla/Spring-cloud-Kubernetes/service.yml:latest
