kind: Service
apiVersion: v1
metadata:
  name: Spring-cloud-Kubernetes
spec:
  type: LoadBalancer
  selector:
    app: Spring-cloud-Kubernetes
  ports:
    - name: http
      protocol: TCP
      # ELB's port
      port: 8081
